-- data.sql

INSERT INTO product (name, description, price, stock_quantity) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI', 29.99, 150),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard with blue switches', 89.99, 50),
('USB-C Cable', 'Durable USB-C cable, 2 meters long', 12.99, 300),
('Gaming Monitor', '27-inch 144Hz gaming monitor with HDR support', 299.99, 25),
('Bluetooth Headphones', 'Over-ear headphones with noise cancellation', 99.99, 75),
('Smartphone Stand', 'Adjustable stand for smartphones and tablets', 19.99, 200),
('Portable Charger', '10000mAh power bank with fast charging', 39.99, 120),
('External Hard Drive', '1TB external hard drive with USB 3.0 support', 59.99, 80),
('Laptop Sleeve', 'Water-resistant sleeve for 13-inch laptops', 24.99, 150),
('Smart LED Bulb', 'WiFi-enabled smart LED bulb with color control', 14.99, 220),
('Wireless Earbuds', 'Compact earbuds with touch control and long battery life', 49.99, 95),
('Fitness Tracker', 'Waterproof fitness tracker with heart rate monitor', 69.99, 100),
('Desk Lamp', 'LED desk lamp with adjustable brightness', 34.99, 130),
('Webcam', '1080p HD webcam with built-in microphone', 49.99, 60),
('Smart Speaker', 'Voice-controlled smart speaker with streaming capabilities', 79.99, 85),
('Electric Kettle', '1.5L electric kettle with auto shut-off', 29.99, 70),
('Coffee Grinder', 'Electric coffee grinder with stainless steel blades', 39.99, 90),
('Air Purifier', 'HEPA air purifier with three-speed fan', 129.99, 40),
('Cordless Vacuum', 'Lightweight cordless vacuum cleaner', 149.99, 35),
('Digital Thermometer', 'Infrared thermometer for non-contact measurements', 19.99, 250),
-- Add 80 more rows here
('Smart Watch', 'Touchscreen smart watch with fitness tracking features', 99.99, 120),
('Wireless Charger', 'Fast wireless charging pad for compatible devices', 29.99, 200),
('Electric Toothbrush', 'Rechargeable electric toothbrush with multiple modes', 59.99, 140),
('Action Camera', 'Waterproof action camera with 4K recording', 199.99, 50),
('Noise-Cancelling Headphones', 'High-quality over-ear headphones with ANC', 249.99, 45),
('Smart Thermostat', 'Programmable thermostat with remote control via app', 149.99, 60),
('Streaming Stick', 'HD streaming stick for TV with voice control', 49.99, 80),
('Standing Desk', 'Height-adjustable standing desk with sturdy frame', 399.99, 20),
('3D Printer', 'Compact 3D printer for home use with high precision', 499.99, 10),
('Gaming Chair', 'Ergonomic gaming chair with lumbar support', 199.99, 25),
('Portable Speaker', 'Bluetooth speaker with 360-degree sound', 79.99, 110),
('Security Camera', 'Wireless security camera with night vision', 89.99, 75),
('Photo Printer', 'Compact photo printer with wireless connectivity', 129.99, 30),
('Electric Scooter', 'Foldable electric scooter with long battery life', 599.99, 15),
('Water Bottle', 'Insulated stainless steel water bottle', 19.99, 300),
('Yoga Mat', 'Non-slip yoga mat with extra cushioning', 29.99, 150),
('Hair Dryer', 'Professional-grade hair dryer with ionic technology', 79.99, 80),
('Electric Shaver', 'Rechargeable electric shaver with precision trimmer', 99.99, 70),
('Robot Vacuum', 'Smart robot vacuum cleaner with mapping technology', 249.99, 30),
('Smart Scale', 'Digital bathroom scale with body composition analysis', 49.99, 95),
('Wireless Router', 'High-speed wireless router with dual-band support', 129.99, 40),
('Electric Blanket', 'Heated electric blanket with adjustable temperature', 79.99, 60),
('Board Game', 'Strategy board game for family and friends', 39.99, 120),
('Portable Fan', 'USB-powered portable fan with adjustable speed', 14.99, 250),
('Electric Skillet', 'Non-stick electric skillet with adjustable thermostat', 49.99, 60),
('Standing Mixer', 'Professional-grade standing mixer with multiple attachments', 399.99, 20),
('Blender', 'High-speed blender with glass jar', 99.99, 50),
('Electric Guitar', 'Beginner-friendly electric guitar with accessories', 199.99, 25),
('Drum Kit', 'Compact electronic drum kit for practice', 299.99, 15),
('Book Light', 'Clip-on book light with adjustable brightness', 12.99, 300),
('Wireless Keyboard', 'Slim wireless keyboard with ergonomic design', 29.99, 150),
('Mouse Pad', 'Large mouse pad with smooth surface', 14.99, 250),
('Smart Doorbell', 'Video doorbell with motion detection and app control', 149.99, 50),
('Noise Machine', 'White noise machine for better sleep', 39.99, 100),
('Sewing Machine', 'Compact sewing machine with multiple stitch options', 129.99, 25),
('Tool Set', 'Complete tool set for home repairs', 59.99, 70),
('Camping Tent', 'Four-person camping tent with waterproof material', 129.99, 40),
('Backpack', 'Durable backpack with laptop compartment', 49.99, 120),
('Binoculars', 'Compact binoculars with high magnification', 79.99, 80),
('Air Fryer', 'Oil-free air fryer with digital controls', 99.99, 70),
('Pressure Cooker', 'Multi-function electric pressure cooker', 119.99, 50),
('Smart Plug', 'WiFi-enabled smart plug with app control', 19.99, 200),
('Cordless Drill', 'Powerful cordless drill with rechargeable battery', 79.99, 60),
('Kitchen Scale', 'Digital kitchen scale with precision measurement', 19.99, 150),
('Pizza Stone', 'Ceramic pizza stone for oven and grill', 29.99, 80),
('Ice Maker', 'Portable ice maker with quick production', 129.99, 40),
('Gaming Headset', 'Wired gaming headset with surround sound', 59.99, 90),
('Massage Gun', 'Handheld massage gun for muscle recovery', 149.99, 35),
('Electric Chainsaw', 'Lightweight electric chainsaw for home use', 199.99, 20),
('Patio Heater', 'Outdoor patio heater with adjustable heat settings', 249.99, 15),
('Bike Helmet', 'Safety bike helmet with adjustable straps', 29.99, 100),
('Garden Hose', 'Flexible garden hose with spray nozzle', 39.99, 150),
('Dog Bed', 'Comfortable dog bed with washable cover', 49.99, 80),
('Cat Tree', 'Multi-level cat tree with scratching posts', 89.99, 30),
('Bird Feeder', 'Durable bird feeder for outdoor use', 24.99, 120);
